[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-client = { version = "0.31.1", features = ["async"] }
anchor-lang = "0.31.1"
anyhow = "1.0.93"
tokio = { version = "1.0", features = ["full"] }