[features]
seeds = false
skip-lint = false
[programs.devnet]
counter = "12kUNNEjTuwtcw1nYGnF6Dtw8K4298BcYyJXFEkNWGDL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/taotalk/Downloads/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
